- job:
    name: nodepool-functional-py35
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-py35/run.yaml
    post-run: playbooks/nodepool-functional-py35/post.yaml
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/nodepool

- job:
    name: nodepool-functional-py35-src
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-py35-src/run.yaml
    post-run: playbooks/nodepool-functional-py35-src/post.yaml
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/glean
      - openstack-infra/nodepool
      - openstack-infra/shade
      - openstack/diskimage-builder

- job:
    name: nodepool-zuul-functional
    parent: tox
    description: |
      Test that zuul works with current nodepool sources.

      This test runs the zuul project ``nodepool`` environment.
    pre-run: playbooks/nodepool-zuul-functional/pre.yaml
    required-projects:
      - openstack-infra/nodepool
      - openstack-infra/zuul
    vars:
      zuul_work_dir: "{{ zuul.projects['git.openstack.org/openstack-infra/zuul'].src_dir }}"
      tox_envlist: nodepool

- project:
    check:
      jobs:
        - tox-docs
        - tox-cover
        - tox-pep8
        - tox-py35
        - nodepool-functional-py35:
            voting: false
        - nodepool-functional-py35-src:
            voting: false
    gate:
      jobs:
        - tox-pep8
        - tox-py35
    experimental:
      jobs:
        - nodepool-zuul-functional
