- job:
    name: nodepool-zuul-functional
    parent: tox
    description: |
      Test that zuul works with current nodepool sources.

      This test runs the zuul project ``nodepool`` environment.
    pre-run: playbooks/nodepool-zuul-functional/pre.yaml
    post-run: playbooks/nodepool-zuul-functional/post.yaml
    required-projects:
      - openstack-infra/nodepool
      - openstack-infra/zuul
    vars:
      zuul_work_dir: "{{ zuul.projects['git.openstack.org/openstack-infra/zuul'].src_dir }}"
      tox_envlist: nodepool

# NOTE(ianw): this job doesn't really do anything unless you set
# "NODEPOOL_PAUSE_something_DIB: false" to unpause one or more builds.
- job:
    name: nodepool-functional-base
    parent: devstack
    pre-run: playbooks/nodepool-functional-base/pre.yaml
    post-run: playbooks/nodepool-functional-base/post.yaml
    timeout: 5400
    required-projects:
      - openstack-infra/nodepool
    vars:
      devstack_localrc:
        USE_PYTHON3: True
      devstack_services:
        horizon: false
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        cinder: false
        c-bak: false
        c-sch: false
        c-api: false
        c-vol: false
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      devstack_plugins:
        nodepool: https://git.openstack.org/openstack-infra/nodepool
      zuul_copy_output:
        '/var/log/nodepool/builds': 'logs'

- job:
    name: nodepool-functional-py35
    parent: nodepool-functional-base
    description: |
      Run nodepool functional tests for py35
    run: playbooks/nodepool-functional-py35/run.yaml
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_UBUNTU_XENIAL_DIB: false

- job:
    name: nodepool-functional-py35-src-base
    parent: nodepool-functional-base
    run: playbooks/nodepool-functional-py35-src/run.yaml
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: shade,glean,diskimage-builder
    required-projects:
      - openstack-infra/glean
      - openstack-infra/nodepool
      - openstack-infra/shade
      - openstack/diskimage-builder

- job:
    name: nodepool-functional-py35-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_UBUNTU_XENIAL_DIB: false

# Distro functional tests.  This is used by projects such as
# diskimage-builder and glean as live-boot tests
- job:
    name: nodepool-functional-py35-redhat-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_CENTOS_7_DIB: false
        NODEPOOL_PAUSE_FEDORA_27_DIB: false

- job:
    name: nodepool-functional-py35-suse-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_OPENSUSE_423_DIB: false
        NODEPOOL_PAUSE_OPENSUSE_TUMBLEWEED_DIB: false

- job:
    name: nodepool-functional-py35-gentoo-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_GENTOO_17_0_SYSTEMD_DIB: false

- job:
    name: nodepool-functional-py35-ubuntu-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_UBUNTU_BIONIC_DIB: false
        NODEPOOL_PAUSE_UBUNTU_XENIAL_DIB: false
        NODEPOOL_PAUSE_UBUNTU_TRUSTY_DIB: false

- job:
    name: nodepool-functional-py35-debian-src
    parent: nodepool-functional-py35-src-base
    vars:
      devstack_localrc:
        NODEPOOL_PAUSE_DEBIAN_JESSIE_DIB: false

- project:
    check:
      jobs:
        - tox-cover
        - tox-pep8
        - tox-py35
        - nodepool-zuul-functional:
            voting: false
        - nodepool-functional-py35:
            voting: false
        - nodepool-functional-py35-src:
            voting: false
        - build-sphinx-docs:
            vars:
              sphinx_python: python3
    gate:
      jobs:
        - tox-pep8
        - tox-py35
        - build-sphinx-docs:
            vars:
              sphinx_python: python3
    post:
      jobs:
        - publish-zuul-docs
        - publish-openstack-sphinx-docs-infra-python3
