- job:
    name: nodepool-functional-py35
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-py35/run.yaml
    post-run: playbooks/nodepool-functional-py35/post.yaml
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/nodepool

- job:
    name: nodepool-functional-py35-src
    parent: legacy-dsvm-base
    run: playbooks/nodepool-functional-py35-src/run.yaml
    post-run: playbooks/nodepool-functional-py35-src/post.yaml
    timeout: 5400
    required-projects:
      - openstack-infra/devstack-gate
      - openstack-infra/glean
      - openstack-infra/nodepool
      - openstack-infra/shade
      - openstack/diskimage-builder

- job:
    name: nodepool-zuul-functional
    parent: legacy-base
    run: playbooks/nodepool-zuul-functional/run.yaml
    post-run: playbooks/nodepool-zuul-functional/post.yaml
    timeout: 1800
    required-projects:
      - openstack-infra/nodepool
      - openstack-infra/zuul

- project:
    check:
      jobs:
        - tox-docs
        - tox-cover
        - tox-pep8
        - tox-py35
        - nodepool-functional-py35:
            voting: false
        - nodepool-functional-py35-src:
            voting: false
    gate:
      jobs:
        - tox-pep8
        - tox-py35
    experimental:
      jobs:
        - nodepool-zuul-functional
